### ISSUE TITLE
Applications not loaded from .local/share/applications in Lubuntu 19.04

### ISSUE THREAD

**Issue by eligt** [SynapseProject/synapse.core.net#99]
I just upgraded to Lubuntu 19.04 and desktop files residing inside `.local/share/applications` don't seem to be loaded anymore. It was working fine in 18.04.

One thing I noticed is when I installed the system the `.local/share/applications` wasn't there and I had to create it manually.

Using version from repository `0.2.99.4-2`

It seems like restarting Synapse a second time (after boot) does reload the applications correctly.

**Comment by steveshortt** [comment]
Hi @eligt, could you clarify the code branch/repo and how you're using Synapse?

**Comment by eligt** [comment]
I think I got the wrong Synapse, I'm using Synapse: the launcher for Linux on Lubuntu 19.04. 
![Screenshot](https://user-images.githubusercontent.com/2043211/64960292-f3454380-d88a-11e9-8995-69684c9c1594.jpg)

**Comment by eligt** [comment]
Yup, got the wrong Synapse, damn sorry about that.
